### ISSUE TITLE
Free TTS

### ISSUE THREAD

**Issue by Space-00** [yjg30737/pyqt-openai#173]
You are using OpenAI TTS models as the app TTS which needs API, this app was created to give free access to AI models, right? so I have a suggestion for you, instead of using OpenAI TTS for generating AI responses to voice, use this free project that gives free access to Microsoft edge TTS inside python

The project link: https://github.com/rany2/edge-tts

And the best model is "en-US-AvaMultilingualNeural (Female)" in my opinion

**Comment by yjg30737** [comment]
Thanks for suggestion, i will try it out

**Comment by yjg30737** [comment]
This is a little example for you, and seems like i successfully implemented it to pyqt-openai. (Still working for other features to make a new release though)

I've never tried in other OS such as Linux and MacOS and i'm using Linux in VirtrualBox and MacOS in MacInCloud, so i might not able to do sound test such as tts in both. It works in Windows though.

https://github.com/yjg30737/edge-tts-gui

**Comment by Space-00** [comment]
Amazing, nice job man, I knew you would get something great out of it

**Comment by yjg30737** [comment]
https://github.com/user-attachments/assets/a8c8fc1b-1efa-469b-b0f1-36abd3200142

I've implemented just like this.

I don't know if this will work after making a binary file out of this as well, but I'll try and tell you. If this works perfectly, we can add some crazy amount of voices to this, by me or by getting a pull request. I hope it will work.

Also, thanks for following me and give a star.

**Comment by Space-00** [comment]
We have to support each other so a star and follow ks nothing👍🏻

**Comment by yjg30737** [comment]
After making bin file with pyinstaller, this didn't turn out well so i spent almost 5 hours to figure out how to successfully run this without any problems. A LOT Harder than i imagined. But at least i firmly know how to handle executable file when running the application.

In Windows, Linux it works like a charm. (If you install mpv) Don't know about Mac though because i tested in MacInCloud, which doesn't support audio. (Maybe they support it but i'd rather getting the maintainer for Mac than using MacInCloud every time.)

**Comment by yjg30737** [comment]
Wait i take that back it doesn't work in binary state 😥 Maybe i tested in wrong way or something. edge-tts.exe in Scripts "need" Python and that's not what i intended when it comes to deployment.

But, oh well, it works when we're running VividNode with "python main.py" and since we are developers after all, that is good enough. Case closed. Mission accomplished!
