### ISSUE TITLE
Vision functionality?

### ISSUE THREAD

**Issue by sm18lr88** [yjg30737/pyqt-openai#92]
do you plan to add any image-uploading functionality?

thanks.

**Comment by yjg30737** [comment]
Definitely. I will add to pyqt-openai in a couple of days.

**Comment by yjg30737** [comment]
There you go! This is gotta be working, if i didn't mess up again even though i did test all the time.

Currently, you can do it only without stream. I will support stream and need refactoring this complicated code as soon as possible, but it might not likely in this year, because Christmas is near.

I add simple guide to README, you can find it [here](https://github.com/yjg30737/pyqt-openai?tab=readme-ov-file#use-gpt-vision)

**Comment by sm18lr88** [comment]
It works, thank you! Now I just have to perfect my prompt because gpt-4-vision is so finicky with its ethical guidelines. It's like on high alert mode in its responses.

You gave me a Christmas gift. Thanks again!
